import type { Metadata } from 'next';
import '../styles/globals.css';
import ReduxProvider from './reduxProvider';
import ReduxDefaultValue from './ReduxProviders/ReduxDefaultValue';
import { WebSocketProvider } from '@/Services/MainWebsocket';

export const metadata: Metadata = {
  title: 'Messanger',
  description: 'Generated by create next app',
};

// بخش layout کلی
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body>
        <ReduxProvider>
          <WebSocketProvider>
            <ReduxDefaultValue>{children}</ReduxDefaultValue>
          </WebSocketProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
